alpaca_eval_gpt4:
  prompt_template: "/home/ke7953/HALOs/alpaca_eval.txt"
  fn_completions: "openai_completions"
  completions_kwargs:
    model_name: "gpt-4.1-mini"
    max_tokens: 100
    temperature: 0
  fn_completion_parser: "ranking_parser"
  batch_size: 1