# Supervised Finetuning
name: sft

trainer: SFTTrainer

dataloader: SFTDataLoader

use_reference_model: false

policy_hf_model_class: AutoModelForCausalLM

reference_hf_model_class: AutoModelForCausalLM