# Simple Preference Optimization

# the temperature parameter for SimPO; controls the saturation
beta: 2.0

# hyperparam for margin size
gamma: 1.0

trainer: SimPOTrainer

dataloader: PairedPreferenceDataLoader